/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_starsecurity_h264_H264Decoder */

#ifndef _Included_com_starsecurity_h264_H264Decoder
#define _Included_com_starsecurity_h264_H264Decoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_starsecurity_h264_H264Decoder
 * Method:    InitDecoder
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_starsecurity_h264_H264Decoder_InitDecoder
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_starsecurity_h264_H264Decoder
 * Method:    UninitDecoder
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_starsecurity_h264_H264Decoder_UninitDecoder
  (JNIEnv *, jclass);

/*
 * Class:     com_starsecurity_h264_H264Decoder
 * Method:    DecoderNal
 * Signature: ([BI[B)I
 */
JNIEXPORT jint JNICALL Java_com_starsecurity_h264_H264Decoder_DecoderNal
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
